language: c
compiler:
    - clang
    - gcc
before_script:
    - wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl
    - chmod +x checkpatch.pl
script: make debug && make check
notifications:
    irc:
        channels:
            - "irc.freenode.org#howm"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
