language: c
compiler:
    - clang
    - gcc
script: make debug
notifications:
    irc:
        channels:
            - "irc.freenode.org#howm"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
        on_success: never
    email: false
